using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

[RequireComponent(typeof(Collider))]
public class PlayerItemManagement : MonoBehaviour
{
    [Tooltip("Playerï¿½ï¿½Itemï¿½Cï¿½ï¿½ï¿½xï¿½ï¿½ï¿½gï¿½ï¿½")]
    [SerializeField] private GameObject _itemBoxCanvas;
    [Tooltip("ItemButtonPreFab, ï¿½Cï¿½ï¿½ï¿½xï¿½ï¿½ï¿½gï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½Button")]
    [SerializeField] private GameObject _itemButton;
    [Tooltip("Itemï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½panel")]
    [SerializeField] private GameObject _itemPanel;
    [Tooltip("Playerï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Aï¿½Cï¿½eï¿½ï¿½")]
    [SerializeField] public List<string> PlayerItemList = new();
    [Tooltip("Playerï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½z")]
    [SerializeField] public int PlayerMoney = 0;
    private bool _trrigerPrime = false;
    private ItemBase _hitItem;

    private void Start()
    {
        if (_itemBoxCanvas == null || _itemButton == null || _itemPanel == null)
        {
            Debug.Log("ï¿½Aï¿½^ï¿½bï¿½`ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½Óï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½");
        }
    }
    public void KeyProcess(ItemBase _hitObject)
    {
            //ItemBoxï¿½Ìqï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Æ‚ï¿½ï¿½ï¿½Buttonï¿½ğ¶ï¿½ï¿½ï¿½ï¿½ï¿½
            var InstantiateObj = Instantiate(_itemButton, _itemBoxCanvas.transform);

            //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Buttonï¿½ï¿½OnClickï¿½ï¿½ItemBaseï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½Ç‰ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
            InstantiateObj.GetComponent<Button>().onClick.AddListener(() => _hitObject.Action());
            InstantiateObj.GetComponentInChildren<Text>().text = _hitObject.GetItemName;
            Debug.Log("yobareta");
            PlayerItemList.Add(_hitObject.GetItemName);
            //_hitObject.ItemOFF();
            //_itemPanel.SetActive(false);
    }

    // void ItemBoxChanger()
    // {
    //     if (_itemBoxCanvas.activeSelf)
    //     {
    //         if (_hitItem != null)
    //         {
    //             _itemPanel.SetActive(true);
    //         }

    //         _itemBoxCanvas.SetActive(false);
    //     }
    //     else
    //     {
    //         if (_itemPanel.activeSelf)
    //         {
    //             _itemPanel.SetActive(false); 
    //         }

    //         _itemBoxCanvas.SetActive(true);
    //     }
    // }

    // private void Update()
    // {
    //     if (Input.GetKeyDown(KeyCode.B))
    //     {
    //         ItemBoxChanger();
    //     }
    //     if (_hitItem != null && Input.GetKeyDown(KeyCode.F))
    //     {
    //         KeyProcess(_hitItem);
    //     }
    // }

    // private void OnTriggerEnter(Collider other)
    // {
    //     _trrigerPrime = true;
        
    //     if (other.gameObject.TryGetComponent(out ItemBase item))
    //     {
    //         _hitItem = item;
    //     }


    //     // if (_hitItem != null && !_itemBoxCanvas.activeSelf)
    //     // {
    //     //     _itemPanel.SetActive(true);
    //     //     _itemPanel.GetComponentInChildren<Text>().text = $"F {_hitItem.GetItemName}";
    //     // }
    //     //KeyProcess(other.gameObject);
    // }

    // private void OnTriggerExit(Collider other)
    // {
    //     _trrigerPrime = false;
    //     _hitItem = null;

    //     if (_itemPanel.activeSelf)
    //     {
    //         _itemPanel.SetActive(false);
    //     }
    // }

    //void ClickProcess()//ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
    //{
    //    Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);

    //    if (Physics.Raycast(ray, out RaycastHit hit))
    //    {
    //        //Rayï¿½ï¿½ï¿½Î‚ï¿½ï¿½Ä‘ÎÛ‚ï¿½ItemBaseï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ê‡ï¿½Éï¿½ï¿½s
    //        if (hit.collider.gameObject.TryGetComponent<ItemBase>(out ItemBase itemBase))
    //        {
    //            //ItemBoxï¿½Ìqï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Æ‚ï¿½ï¿½ï¿½Buttonï¿½ğ¶ï¿½ï¿½ï¿½ï¿½ï¿½
    //            var InstantiateObj = Instantiate(_itemButton, _itemCanvas.transform);
    //            //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Buttonï¿½ï¿½OnClickï¿½ï¿½ItemBaseï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½Ç‰ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
    //            InstantiateObj.GetComponent<Button>().onClick.AddListener(() => itemBase.Action());
    //            InstantiateObj.GetComponentInChildren<Text>().text = itemBase.GetItemName;
    //            _itemList.Add(InstantiateObj);
    //            itemBase.ItemOFF();
    //        }
    //    }
    //}

}